// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4oB_Bdxtgj-eH-nMBQgV_ArLp53hF8TA',
    appId: '1:88859348373:android:1cbf9bd1d3f60eb5a6fa9c',
    messagingSenderId: '88859348373',
    projectId: 'wechat-51d16',
    databaseURL: 'https://wechat-51d16-default-rtdb.firebaseio.com',
    storageBucket: 'wechat-51d16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzSgU9FdaDivlmoOyGKHBXmCXw7D8KEqg',
    appId: '1:88859348373:ios:dedc05e319829e89a6fa9c',
    messagingSenderId: '88859348373',
    projectId: 'wechat-51d16',
    databaseURL: 'https://wechat-51d16-default-rtdb.firebaseio.com',
    storageBucket: 'wechat-51d16.appspot.com',
    androidClientId: '88859348373-7v93ggen13mn3vrlrtjl4b5apvolf4n1.apps.googleusercontent.com',
    iosClientId: '88859348373-ut4kb22gjuatrqi66er5umpmtd21fr5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampark',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6CRc2y_Tw42XCgGShID0MUl6P-y-eyPQ',
    appId: '1:88859348373:web:c0a36c3093737aaaa6fa9c',
    messagingSenderId: '88859348373',
    projectId: 'wechat-51d16',
    authDomain: 'wechat-51d16.firebaseapp.com',
    databaseURL: 'https://wechat-51d16-default-rtdb.firebaseio.com',
    storageBucket: 'wechat-51d16.appspot.com',
    measurementId: 'G-0FB6BX825H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzSgU9FdaDivlmoOyGKHBXmCXw7D8KEqg',
    appId: '1:88859348373:ios:dedc05e319829e89a6fa9c',
    messagingSenderId: '88859348373',
    projectId: 'wechat-51d16',
    databaseURL: 'https://wechat-51d16-default-rtdb.firebaseio.com',
    storageBucket: 'wechat-51d16.appspot.com',
    androidClientId: '88859348373-7v93ggen13mn3vrlrtjl4b5apvolf4n1.apps.googleusercontent.com',
    iosClientId: '88859348373-ut4kb22gjuatrqi66er5umpmtd21fr5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sampark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6CRc2y_Tw42XCgGShID0MUl6P-y-eyPQ',
    appId: '1:88859348373:web:ef5fe05833499852a6fa9c',
    messagingSenderId: '88859348373',
    projectId: 'wechat-51d16',
    authDomain: 'wechat-51d16.firebaseapp.com',
    databaseURL: 'https://wechat-51d16-default-rtdb.firebaseio.com',
    storageBucket: 'wechat-51d16.appspot.com',
    measurementId: 'G-DT47SB8V5W',
  );

}